"""empty message

Revision ID: c945a5acfea7
Revises: 
Create Date: 2022-06-30 18:43:08.722788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c945a5acfea7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stringjwt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('string', sa.String(length=256), nullable=False),
    sa.Column('access_token', sa.String(length=256), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delete_flag', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stringjwt')
    # ### end Alembic commands ###
